### ISSUE TITLE
Panic on restarting oklog docker container multiple times. 

### ISSUE THREAD

**Issue by adnaan** [oklog/oklog#102]
I have a docker compose file setup like this:

```
... 
oklog: 
    build: ./oklog
    container_name: ${OKLOG_CONTAINER_NAME}
    command: ingeststore -store.segment-replication-factor 1
    ports: 
      - 7651:7651
      - 7650:7650
      - 7653:7653
      - 7659:7659
    volumes:
      - ${OSX_LOG_DIR}:/data
    
  logspout: 
    image: gliderlabs/logspout
    container_name: ${LOGSPOUT_CONTAINER_NAME}
    command: raw+tcp://${OKLOG_CONTAINER_NAME}:7651
    depends_on:
      - oklog
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - oklog
```

After multiple `docker-compose up` and `docker-compose down` commands(there doesn't seem to be a consistency to the number of ups and downs), the oklog container panics with:

```
$docker logs -f oklog
ts=2018-02-02T19:16:00.101587594Z level=info cluster_bind=0.0.0.0:7659
ts=2018-02-02T19:16:00.110157207Z level=info user_bind_host=0.0.0.0 user_advertise_host= calculated_advertise_ip=172.18.0.2
ts=2018-02-02T19:16:00.112425772Z level=info fast=tcp://0.0.0.0:7651
ts=2018-02-02T19:16:00.112505032Z level=info durable=tcp://0.0.0.0:7652
ts=2018-02-02T19:16:00.112891239Z level=info bulk=tcp://0.0.0.0:7653
ts=2018-02-02T19:16:00.113107131Z level=info API=tcp://0.0.0.0:7650
ts=2018-02-02T19:16:00.161997474Z level=info ingest_path=data/ingest
ts=2018-02-02T19:16:07.109384344Z level=info store_path=data/store
panic: close data/store/bcd73f75-18ce-415e-ad9b-bf4025fd7755.active: file already closed

goroutine 47 [running]:
github.com/oklog/oklog/pkg/store.mergeRecordsToLog.func1(0xc420455b38)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/pkg/store/read.go:150 +0x65
github.com/oklog/oklog/pkg/store.mergeRecordsToLog(0xd6a200, 0xc42007a410, 0x8000000, 0xc42011d180, 0x34, 0x34, 0x100001a0, 0xd5e780, 0xc420166040)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/pkg/store/read.go:239 +0xa9e
github.com/oklog/oklog/pkg/store.(*Compacter).compact(0xc420068b40, 0xa4e1e9, 0xb, 0xc42003edf0, 0x0, 0x0, 0x0)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/pkg/store/compact.go:126 +0x2f7
github.com/oklog/oklog/pkg/store.(*Compacter).Run.func1()
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/pkg/store/compact.go:52 +0x71
github.com/oklog/oklog/pkg/store.(*Compacter).Run(0xc420068b40)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/pkg/store/compact.go:62 +0x2f5
main.runIngestStore.func14(0x0, 0x0)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/cmd/oklog/ingeststore.go:441 +0x2a
github.com/oklog/oklog/vendor/github.com/oklog/run.(*Group).Run.func1(0xc420068ba0, 0xc420040ec0, 0xc420040ef0)
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/oklog/vendor/github.com/oklog/run.(*Group).Run
	/Users/adnaan/code/gopath/src/github.com/oklog/oklog/vendor/github.com/oklog/run/group.go:37 +0xa8
```

I found the issue for 0.3.0 release and rebuilt oklog:master to check if it's already fixed.

Thank you.
