### ISSUE TITLE
integration: Docker

### ISSUE THREAD

**Issue by peterbourgon** [oklog/oklog#18]
Like #13, we should provide a simple drop-in integration for plain Docker hosts.

**Comment by seiflotfy** [comment]
Could this be done via logspout?

**Comment by peterbourgon** [comment]
> Could this be done via logspout?

At a first glance, yes, absolutely. I'm slightly more comfortable with a non-Dockerized solution, but maybe that juice ain't worth the squeeze...

**Comment by peterbourgon** [comment]
[Well, that was easy](https://github.com/oklog/oklog/wiki/Integrations#docker). Thanks for the suggestion, @seiflotfy!

**Comment by drozzy** [comment]
@peterbourgon Could you provide an extended example? I'm afraid I don't understand what is going on here...

My use case is I have many docker services composed with docker-compose. I would like all of them to send their logs to oklog.
I think this is a very popular use case (ELK stack has many example of such an integration).

I would appreciate it very much, as OKLog seems to be exactly what I need.

Thank you!

**Comment by xla** [comment]
@drozzy You should be able to extend your compose file with the logspout container and configure it with your oklog ingest endpoint configured much like the example.

**Comment by drozzy** [comment]
@xla Can I just use one oklog service? (The docs mention you need 2 minimum..)

**Comment by drozzy** [comment]
I'm trying this:
```
version: "3"

volumes:
    oklog:

services:
    whalesay:
        image: docker/whalesay
        depends_on:
        - logspout

    logspout:
        image: gliderlabs/logspout
        command:
            - "syslog+tcp://oklog:7651"
        ports:
            - "8000:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        depends_on:
            - oklog
    oklog:
        image: oklog/oklog
        volumes:
            - oklog:/data
```

but both services stop:
```
logspout_1  | # logspout v3.2.4 by gliderlabs
logspout_1  | # adapters: tls raw syslog tcp udp
logspout_1  | # options : persist:/mnt/routes
logspout_1  | !! lookup oklog on 127.0.0.11:53: no such host
oklog_1     | USAGE
oklog_1     |   /oklog <mode> [flags]
oklog_1     | 
oklog_1     | MODES
oklog_1     |   forward      Forwarding agent
oklog_1     |   ingest       Ingester node
oklog_1     |   store        Storage node
oklog_1     |   ingeststore  Combination ingest+store node, for small installations
oklog_1     |   query        Querying commandline tool
oklog_1     |   stream       Streaming commandline tool
oklog_1     |   testsvc      Test service, emits log lines at a fixed rate
oklog_1     | 
oklog_1     | VERSION
oklog_1     |   0.2.2 (go1.8.3)
oklog_1     | 
```

I tried putting them on the same network, but no cigar:

```
version: "3"

volumes:
    oklog:

services:
    whalesay:
        image: docker/whalesay
        depends_on:
        - logspout

    logspout:
        image: gliderlabs/logspout
        command:
            - "syslog+tcp://oklog:7651"
        ports:
            - "8000:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - logging
        depends_on:
            - oklog
    oklog:
        image: oklog/oklog
        volumes:
            - oklog:/data
        networks:
            - logging

networks:
    logging:
    
```


Still get:

```
logspout_1  | # logspout v3.2.4 by gliderlabs
logspout_1  | # adapters: raw syslog tcp udp tls
logspout_1  | # options : persist:/mnt/routes
logspout_1  | !! lookup oklog on 127.0.0.11:53: no such host
oklog_1     | USAGE
oklog_1     |   /oklog <mode> [flags]
oklog_1     | 
oklog_1     | MODES
oklog_1     |   forward      Forwarding agent
oklog_1     |   ingest       Ingester node
oklog_1     |   store        Storage node
oklog_1     |   ingeststore  Combination ingest+store node, for small installations
oklog_1     |   query        Querying commandline tool
oklog_1     |   stream       Streaming commandline tool
oklog_1     |   testsvc      Test service, emits log lines at a fixed rate
oklog_1     | 
oklog_1     | VERSION
oklog_1     |   0.2.2 (go1.8.3)
oklog_1     | 

```

**Comment by drozzy** [comment]
Oh, wait, I think I almost got it.

**Comment by drozzy** [comment]
Ok, here is the minimal working example:

Just run:

    docker-compose up -d

and run it again to produce another "Hello World" message. UI can be accessed via: http://localhost:7650/ui/

```
version: "3"

volumes:
    oklog:

services:
    test:
        image: ubuntu:latest 
        command: echo Hello World
        depends_on:
            - logspout

    logspout:
        image: gliderlabs/logspout
        command:
            - "syslog+tcp://oklog:7651"
        ports:
            - "8000:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        depends_on:
            - oklog
        networks:
            - logging

    oklog:
        image: oklog/oklog
        volumes:
            - oklog:/data
        ports:
            - 7650:7650
            
        command: ingeststore -store.segment-replication-factor 1
        networks:
            - logging

# We need a common network because logspout sends data to oklog
networks:
    logging:
```

I must say, UI is a bit strange. It shows the same message multiple times, and it's not very clear how "Streaming" behaves. It seems to reset every time I refresh the page.
